### PR TITLE
fix(spans): adhere attribute name to otel semver

### LINKED ISSUE #182: http - align OTEL http attributes with latest standard
to maintain compatibility with external tooling we should make sure our attribute respect the latest (stable) semantic conventions. When we initially implemented things, the spec was still in draft. The following attributes need to be renamed in the middleware handlers and in the request adapter:
htttp.status_code => http.response.status_code
http.response_content_length => http.response.body.size
http.request_content_length => http.request.body.size
http.flavor => network.protocol.name
http.response_content_type => http.response.header.content-type
http.request_content_type => http.request.header.content-type
http.method => http.request.method
http.host => url.scheme
http.scheme => server.address
http.uri => url.full
http.uri_template => url.uri_template

link to the spec for more information https://opentelemetry.io/docs/specs/semconv/attributes-registry/http/
related https://github.com/microsoftgraph/msgraph-sdk-design/pull/108

### PR DESCRIPTION
**Pull request by Strazz1337**
Updates the http span attributes to match with the updated OTEL specification.

Fixes #182

### CODE REVIEW

File: compression_handler.go [hunk 1]
```diff
@@ -120,8 +121,8 @@ func (c *CompressionHandler) Intercept(pipeline Pipeline, middlewareIndex int, r
 		req.ContentLength = unCompressedContentLength
 
 		if span != nil {
-			span.SetAttributes(attribute.Int64("http.request_content_length", req.ContentLength),
-				attribute.Int("http.request_content_length", 415))
+			span.SetAttributes(semconv.HTTPRequestBodySize(int(req.ContentLength)),
+				semconv.HTTPResponseStatusCode(415))
```
Comment (Strazz1337) [inline compression_handler.go:125]: It feels off that the second attribute is the same as the first one. So I set it to `HTTPResponseStatusCode`, as I expect it to equal the status code that is checked a few lines before this.

File: compression_handler.go [hunk 2]
```diff
@@ -10,6 +10,7 @@ import (
 	abstractions "github.com/microsoft/kiota-abstractions-go"
 	"go.opentelemetry.io/otel"
 	"go.opentelemetry.io/otel/attribute"
+	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
```
Comment (andrueastman) [inline compression_handler.go:13]:
```suggestion
	semconv "go.opentelemetry.io/otel/semconv"
```
Should the imports include the version here? Or will they cause issue incase of an update in the go.mod file?

Comment (Strazz1337) [reply compression_handler.go:13]: It did not work when I did not assign the version here. So if you manage to get it working that'd be great :)

Comment (musale) [reply compression_handler.go:13]: @andrueastman you need to reference the version and yes, it will cause runtime errors if you upgrade the otel sdk and don't have the correct version of `semconv` referenced. I hace seen multiple issues and proposals for this but no progress I'm aware of to mitigate having to update all references of `semconv` usage. See https://github.com/open-telemetry/opentelemetry-go/issues/4886

Comment (baywet) [reply compression_handler.go:13]: In general we've faced similar issues in other languages. This dependency causes a lot of issues since they ship breaking changes without major revs (to keep the version aligned with the other packages roughly). We've resulted NOT to use this package in other languages because of that. Yes it introduces misalignment possibilities/added maintenance burden because of that.
I hope this additional context helps!

**Comment by baywet** [comment]
@Strazz1337 gentle reminder on this one. Are you still working on it?

**Comment by Strazz1337** [comment]
@baywet fixed. 

Somehow git sees the following files as fully changed, while only the setAttributes methods are clearly updated:
- compression_handler.go
- retry_handler.go

File: span_attributes.go [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+const (
+	HttpRequestBodySizeAttribute    = attribute.Key("http.request.body.size")
+	HttpRequestResendCountAttribute = attribute.Key("http.request.resend_count")
+	HttpRequestMethodAttribute      = attribute.Key("http.request.method")
+)
+
+// HTTP Response attributes
+const (
+	HttpResponseBodySizeAttribute          = attribute.Key("http.response.body.size")
+	HttpResponseHeaderContentTypeAttribute = attribute.Key("http.response.header.content_type")
```
Comment (baywet) [inline span_attributes.go:15]:
```suggestion
	HttpResponseHeaderContentTypeAttribute = attribute.Key("http.response.header.content-type")
```

File: span_attributes.go [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+// Server attributes
+const (
+	ServerAddressAttribute = attribute.Key("server.address")
+)
+
+// URL attributes
+const (
+	UrlFullAttribute      = attribute.Key("url.full")
+	UrlSchemeAttribute    = attribute.Key("url.scheme")
+	UrlUriSchemeAttribute = attribute.Key("url.uri_scheme")
```
Comment (baywet) [inline span_attributes.go:33]:
```suggestion
	UrlUriTemplateAttribute = attribute.Key("url.uri_template")
```

File: nethttp_request_adapter.go [hunk 5]
```diff
@@ -313,7 +313,7 @@ func (a *NetHttpRequestAdapter) startTracingSpan(ctx context.Context, requestInf
 	decodedUriTemplate := decodeUriEncodedString(requestInfo.UrlTemplate, []byte{'-', '.', '~', '$'})
 	telemetryPathValue := queryParametersCleanupRegex.ReplaceAll([]byte(decodedUriTemplate), []byte(""))
 	ctx, span := otel.GetTracerProvider().Tracer(a.observabilityOptions.GetTracerInstrumentationName()).Start(ctx, methodName+" - "+string(telemetryPathValue))
-	span.SetAttributes(attribute.String("http.uri_template", decodedUriTemplate))
+	span.SetAttributes(UrlUriSchemeAttribute.String(decodedUriTemplate))
```
Comment (baywet) [inline nethttp_request_adapter.go:316]:
```suggestion
	span.SetAttributes(UrlUriTemplateAttribute.String(decodedUriTemplate))
```

File: CHANGELOG.md [hunk 6]
```diff
@@ -12,6 +12,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Changed
 
 - Fixed a bug where headers inspection handler would fail upon receiving an error.
```
Comment (baywet) [inline CHANGELOG.md:14]: needs to move to a new version
And the version in the user agent handler needs to be bumped

File: nethttp_request_adapter.go [hunk 7]
```diff
@@ -290,14 +290,14 @@ func (a *NetHttpRequestAdapter) getRequestFromRequestInformation(ctx context.Con
 		}
 		if request.Header.Get("Content-Type") != "" {
 			spanForAttributes.SetAttributes(
-				attribute.String("http.request_content_type", request.Header.Get("Content-Type")),
+				attribute.String("http.request.header.content-type", request.Header.Get("Content-Type")),
```
Comment (baywet) [inline nethttp_request_adapter.go:293]: should be moved to the constants to align with the other attributes

**Review by baywet — CHANGES_REQUESTED** [review]
Thank you for making the changes! A couple additional remarks

File: CHANGELOG.md (hunk 6 above)
Comment (baywet) [reply CHANGELOG.md]: fixed

**Review by baywet — APPROVED** [review]
Thanks for the contribution!

Do you want to take on java next? https://github.com/microsoft/kiota-java/issues/1540
